### ISSUE TITLE
Missing secret_key_base

### ISSUE THREAD

**Issue by collimarco** [paketo-buildpacks/rails-assets#144]
Building a Rails app (v6.1.4) with `pack` fails:

```
Paketo Rails Assets Buildpack 0.2.4
  Executing build process
    Running 'bundle exec rails assets:precompile assets:clean'
failed to execute bundle exec output:
rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
/workspace/config/environment.rb:5:in `<main>'
Tasks: TOP => environment
```

Related: https://github.com/rails/rails/issues/32947

The point is that you don't need that key during the assets compile task, so a random key should be passed instead, so that the task doesn't fail.

Can you fix that?

Or can you suggest any other solution?

**Comment by collimarco** [comment]
Note that the Heroku buildpack works properly with the same application, so this is a bug in this buildpack.

**Comment by sophiewigmore** [comment]
Hey @collimarco, thanks for letting us know.

Yes, we've run into this before, which seems like buggy Rails 6 behaviour.  Our [rails 6](https://github.com/paketo-buildpacks/rails-assets/tree/main/integration/testdata/6.0) test app currently gets around this issue by setting `config.secret_key_base = ENV['SECRET_KEY_BASE']` in the [production.rb](https://github.com/paketo-buildpacks/rails-assets/blob/6c46f6022d4fce6d3fb2f4402252bbb7098b6898/integration/testdata/6.0/config/environments/production.rb#L96). 
Then, when running the built image with `docker run`, we pass the dummy vale`--env SECRET_KEY_BASE=something` to make rails happy.

**Comment by sophiewigmore** [comment]
Your suggestion of setting the dummy value in the buildpack is a good idea. I would be open to it if we could check through the app config files to make sure we aren't overriding a user-set value, in a nice, straightforward way.

**Comment by kingdonb** [comment]
The linked thread from rails/rails looks... unresolved

I tried setting `config.secret_key_base = ENV['SECRET_KEY_BASE']` in production.rb but doesn't this still require a SECRET_KEY_BASE to be injected into the environment when you want to precompile assets?

I'm testing on Rails 7 and Ruby 3.1.2, and it's looking like a no-go. I did manage to get this far, it was a bit harder than it should be, but basically just had to ensure I was using the `full` builder (not `base`) and that I was not loading any other buildpacks besides `ruby` first, since it seemingly invokes all the buildpacks that it needs including this one.

I'm trying to get `rails assets:precompile` to work running locally with no master.key and no SECRET_KEY_BASE injected, I would settle for injecting a dummy variable but AFAICT it's not supported through `kpack`:

* https://github.com/pivotal/kpack/issues/458

So, is there a solution that works with kpack? 😄

**Comment by kingdonb** [comment]
This is what I wound up doing for today:

```diff
diff --git a/config/environments/production.rb b/config/environments/production.rb
index 8eea956..5d9946e 100644
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -78,5 +78,5 @@ Rails.application.configure do
   config.active_record.dump_schema_after_migration = false

   # https://github.com/paketo-buildpacks/rails-assets/issues/144#issuecomment-975613426
-  config.secret_key_base = ENV['SECRET_KEY_BASE']
+  config.secret_key_base = ENV['SECRET_KEY_BASE'] || `rails secret`
```

I'd like to add a guard clause to guarantee that I'm not really using a random secret in production where I guess it would cause peoples cookies to be invalidated every time the server starts up, or maybe alternatively if there's a variable set by paketo ruby/rails buildpack that I can use to detect I'm doing assets precompile/build and it's OK to use a random secret... otherwise balk and quit?

This seemed to work! I have an image now, gonna go test it out...

**Comment by kingdonb** [comment]
A little further poking around the documentation, I found that issue I linked is misleading:

```yaml
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: planet-image
  namespace: planet-store
spec:
  tag: img.hephy.pro/planetstore/web
  imageTaggingStrategy: BuildNumber
  serviceAccountName: store-pusher
  builder:
    name: planet-builder
    kind: Builder
  source:
    git:
      url: git@github.com:yebyen/planet-store.git
      revision: production
      #revision: c090ccca4a41096cc1155d20e05ddf9999211754
  build:
    env:
      - name: SECRET_KEY_BASE
        value: asdf1234
```

You can of course set environment variables at build time, in the `Image` definition, that wasn't clear to me until I read the doc (not sure how you can solve that one unfortunately, I'll try to read all the docs...)
